Region: {{ AWS_REGION }}
Image:
  Os: ubuntu2004
HeadNode:
  InstanceType: t2.xlarge
  Networking:
    SubnetId: {{ PUBLIC_SUBNET }}
    ElasticIp: true
  Ssh:
    KeyName: {{ SSH_KEY_PAIR }}
  CustomActions:
    OnNodeStart:
      Script: {{ CUSTOM_BOOT_ACTION_START }}
    OnNodeConfigured:
      Script: {{ CUSTOM_BOOT_ACTION_CONFIGURED }}
      Args:
        - "{{ SLURM_JWT_KEY }}"
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue1
      ComputeResources:
        - Name: t2large
          InstanceType: t2.large
          MinCount: 1
          MaxCount: 2
      Networking:
        SubnetIds:
          - {{ PRIVATE_SUBNET }}
      CustomActions:
        OnNodeStart:
          Script: {{ CUSTOM_BOOT_ACTION_START }}
        OnNodeConfigured:
          Script: {{ CUSTOM_BOOT_ACTION_CONFIGURED }}
          Args:
            - "{{ SLURM_JWT_KEY }}"
SharedStorage:
  - MountDir: /shared
    Name: shared
    StorageType: Efs
    EbsSettings:
      VolumeType: gp2
      Size: 50
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true
  Dashboards:
    CloudWatch:
      Enabled: true
