Region: {{ AWS_REGION }}
Image:
  Os: alinux2
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: {{ PUBLIC_SUBNET }}
  Ssh:
    KeyName: {{ SSH_KEY_PAIR }}
  CustomActions:
    OnNodeConfigured:
      Script: {{ HEAD_NODE_CONFIGURED_SCRIPT }}
      Args:
        - "{{ SLURM_VERSION }}"
        - "{{ SLURM_JWT_KEY }}"
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue1
      ComputeResources:
        - Name: t2micro
          InstanceType: t2.micro
          MinCount: 0
          MaxCount: 2
      Networking:
        SubnetIds:
          - {{ PRIVATE_SUBNET }}
SharedStorage:
  - MountDir: /shared
    Name: shared
    StorageType: Ebs
    EbsSettings:
      VolumeType: gp2
      Size: 50
Monitoring:
  DetailedMonitoring: true
  Logs:
    CloudWatch:
      Enabled: true
  Dashboards:
    CloudWatch:
      Enabled: true
