name: S3 deploy scripts
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: reggionick/s3-deploy@5ed8934a7499373b51337042f7e11b5f7599d7dc
        with:
          folder: .
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          no-cache: true
          filesToInclude: "on_node_configured.sh,on_node_start.sh"
          delete-removed: true
