name: S3 deploy scripts
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.S3_BUCKET_REGION }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: rlkennedyreid/aws-cli-action@v0.1.0
        with:
          args: s3 cp ./on_node_configured.sh s3://${{ secrets.S3_BUCKET }}
